[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "very-good-ffmpeg"
dynamic = ["version"]
description = "Python SDK for the Very Good FFmpeg API"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.hatch.version]
path = "very_good_ffmpeg/_version.py"

[project.urls]
Homepage = "https://verygoodffmpeg.com"
Repository = "https://github.com/verygoodffmpeg/Very-Good-FFmpeg-Python-SDK"
